server {
  listen 80;
  server_name _;

  add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; frame-src 'self' https://idp.ujep.cz; frame-ancestors 'self' https://idp.ujep.cz" always;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}

