services:
  timesheets.database:
    image: public.ecr.aws/docker/library/postgres:17-alpine

  timesheets.backend:
    build:
      target: prebuilt

  timesheets.frontend:
    build:
      target: prebuilt
    ports:
      - "8080:80"
    volumes: []
