export const Texts = {
  applicationName: "VÝKAZY",
  projects: "Projekty",
  contracts: "Zakázky",
  employees: "Zaměstnanci",
  active: "Aktivní",
  inactive: "Neaktivní",
  projectId: "ID projektu",
  addProject: "Přidat projekt",
  searchByNameOrId: "Hledat podle názvu nebo ID…",
  removeFilter: "Vymazat filtr",
  activeOnly: "Pouze aktivní",
  newProject: "Nový projekt",
  projectName: "Název projektu",
  projectIdLabel: "ID projektu",
  startDate: "Datum začátku",
  endDate: "Datum ukončení",
  recipientName: "Název příjemce",
  projectDescription: "Popis projektu",
  confirm: "Potvrdit",
  cancel: "Zrušit",
  searchByNameEmailOrNumber: "Hledat podle jména, emailu, os. čísla…",
  employeesInMyContracts: "Zaměstnanci v mých zakázkách",
  registerEmployee: "Registrovat zaměstnance",
  personalNumber: "Osobní číslo",
  fullName: "Celé jméno",
  email: "E-mail",
  employeeType: "Typ zaměstnance",
  actions: "Akce",
  addEmployeePosition: "Přidat pozici",
  project: "Projekt",
  contract: "Zakázka",
  positionCode: "Kód pozice",
  positionName: "Název pozice",
  workload: "Úvazek",
  academic: "Akademik",
  nonAcademic: "Neakademik",
  actionSuccessful: "Akce byla úspěšně provedena",
  actionFailed: "Akci se nepodařilo provést",
  delete: "Smazat",
  noResults: "Žádné výsledky",
  noDate: "Bez data",
  search: "Hledat…",
  noItems: "Žádné položky",
  confirmAction: "Potvrzení akce",
  confirmActionDescription: "Opravdu si přejete pokračovat? Tuto akci nelze vrátit zpět.",
  dash: "—",
  addPosition: "Přidat pozici",
  registrationNumber: "Číslo zakázky",
  contractName: "Název zakázky",
  newContract: "Nová zakázka",
  contractDescription: "Popis zákazky",
  contractId: "ID zakázky",
  position: "Pozice",
  status: "Status",
};
