export const Routes = {
  projects: () => "/projects",
  project: (id: string) => `/projects/${id}`,
  projectContracts: (id: string) => `/projects/${id}`,
  projectContractsManagers: (id: string) => `/projects/${id}/contracts-managers`,
  contract: (projectId: string, contractId: string) => `/projects/${projectId}/contracts/${contractId}`,
  contractTimesheets: (projectId: string, contractId: string) => `/projects/${projectId}/contracts/${contractId}`,
  contractEmployees: (projectId: string, contractId: string) => `/projects/${projectId}/contracts/${contractId}/employees`,
  employees: () => "/employees",
  employeeRoles: () => "/employees/roles",
  employee: (id: string) => `/employees/${id}`,
  employeePositions: (id: string) => `/employees/${id}/positions`,
  timesheet: (employeeId: string, year: number, month: number) => `/timesheet?employeeId=${employeeId}&year=${year}&month=${month}`,
  resourceProjects: () => "/_resources/projects",
  resourceContracts: (projectId: string) => `/_resources/contracts?projectId=${encodeURIComponent(projectId)}`,
  resourceEmployees: () => "/_resources/employees",
  resourceProjectContracts: (projectId: string) => `/_resources/project-contracts/${projectId}`,
};
