export const Texts = {
  applicationName: "VÝKAZY",
  projects: "Projekty",
  contracts: "Zakázky",
  employees: "Zaměstnanci",
  active: "Aktivní",
  inactive: "Neaktivní",
  projectId: "ID projektu",
  addProject: "Přidat projekt",
  searchByNameOrId: "Hledat podle názvu nebo ID…",
  removeFilter: "Vymazat filtr",
  activeOnly: "Pouze aktivní",
  newProject: "Nový projekt",
  projectName: "Název projektu",
  projectIdLabel: "ID projektu",
  startDate: "Datum začátku",
  endDate: "Datum ukončení",
  recipientName: "Název příjemce",
  projectDescription: "Popis projektu",
  confirm: "Potvrdit",
  cancel: "Zrušit",
  searchByNameEmailOrNumber: "Hledat podle jména, emailu, os. čísla…",
  employeesInMyContracts: "Zaměstnanci v mých zakázkách",
  registerEmployee: "Registrovat zaměstnance",
  personalNumber: "Osobní číslo",
  fullName: "Celé jméno",
  email: "E-mail",
  employeeType: "Typ zaměstnance",
  actions: "Akce",
  addEmployeePosition: "Přidat pozici",
  project: "Projekt",
  contract: "Zakázka",
  positionCode: "Kód pozice",
  positionName: "Název pozice",
  workload: "Úvazek",
  academic: "Akademik",
  nonAcademic: "Neakademik",
  actionSuccessful: "Akce byla úspěšně provedena",
  actionFailed: "Akci se nepodařilo provést",
  delete: "Smazat",
  noResults: "Žádné výsledky",
  noDate: "Bez data",
  search: "Hledat…",
  noItems: "Žádné položky",
  confirmAction: "Potvrzení akce",
  confirmActionDescription: "Opravdu si přejete pokračovat? Tuto akci nelze vrátit zpět.",
  dash: "-",
  addPosition: "Přidat pozici",
  contractName: "Název zakázky",
  newContract: "Nová zakázka",
  editContract: "Upravit zakázku",
  contractDescription: "Popis zákazky",
  contractId: "ID zakázky",
  position: "Pozice",
  status: "Status",
  edit: "Upravit",
  editProject: "Upravit projekt",
  addContract: "Přidat zakázku",
  addManager: "Přidat manažera",
  contractsManagers: "Manažeři zakázek",
  addEmployee: "Přidat zaměstnance",
  from: "Od",
  to: "Do",
  grouping: "Seskupení",
  periodFrom: "Období od",
  periodTo: "Období do",
  groupByEmployee: "Dle zaměstnance a měsíce",
  groupByMonthAndEmployee: "Dle měsíce a zaměstnance",
  timesheetStatus: "Stav výkazu",
  period: "Období",
  statusInProgress: "Rozpracovaný",
  statusPendingApproval: "Ke schválení",
  statusApproved: "Schválený",
  import: "Importovat docházku",
  importFiles: "Importovat docházku",
  importAttendanceOnly: "Lze importovat pouze výkaz pracovní docházky.",
  importDropFiles: "Vyberte soubor nebo ho nahrajte přetažením",
  noFilesSelected: "Zatím nejsou vybrány žádné soubory.",
  remove: "Odebrat",
  importing: "Importuji...",
  noEmployeeSelected: "Není vybrán zaměstnanec",
  noFilesToImport: "Žádné soubory k importu",
  noContractsForImport: "Zaměstnanec nemá žádné kontrakty pro přiřazení výkazů",
  importXlsOnly: "Lze importovat pouze soubory XLS nebo XLSX",
  importSuccessCount: "Úspěšně importováno {count} souborů",
  importFailureCount: "Nepodařilo se importovat {count} souborů",
  importError: "Chyba při importu souborů",
  importProcessing: "Importuje se",
  importSucceeded: "Importováno",
  importFailedSingle: "Import se nezdařil",
  importPeriodLabel: "Období",
  importEmployeeLabel: "Zaměstnanec",
  importPersonalNumberLabel: "Osobní číslo",
  importResultTitle: "Výsledek importu",
  importReady: "Připraveno k importu",
  importCannotImport: "Nelze importovat",
  importDetecting: "Načítají se metadata",
  importBack: "Zpět",
  close: "Zavřít",
  combinedTimesheet: "Kombinovaný výkaz",
  changeTimesheetStatus: "Změnit stav výkazu",
  enterFullscreen: "Fullscreen",
  exitFullscreen: "Ukončit fullscreen",
  saveChanges: "Uložit změny",
  clearAttendanceEntryAndBreak: "Vymazat příchody, odchody a přestávku",
  addEmployeePositionToEmployeeTitle: "Přidat zaměstnanci pozici",
  loading: "Načítání",
  redirectingToLogin: "Přesměrování na přihlášení…",
  user: "Uživatel",
  logout: "Odhlásit",
  notFoundTitle: "Stránka nebyla nalezena",
  notFoundDescription: "Požadovaná stránka buď neexistuje, nebo k ní nemáte přístup.",
  goToOverview: "Přejít na přehled",
  unlockContractColumn: "Odemknout sloupec zakázky",
  lockContractColumn: "Uzamknout sloupec zakázky",
  back: "Zpět",
  selectEmployee: "Vyberte zaměstnance",
  selectProject: "Vyberte projekt",
  selectContract: "Vyberte zakázku",
  enterWholeNumberRange1to100: "Zadejte celé číslo 1–100 (procenta úvazku).",
  enterWholeNumberRange0to100: "Zadejte celé číslo 0–100 (procenta úvazku).",
  employeeAlreadyHasPositionOverlap: "Zaměstnanec už má tuto pozici na zakázce v překrývajícím se období.",
  startDateRequiredLabel: "Datum začátku *",
  endDateLabel: "Datum ukončení",
  timesheets: "Výkazy",
  month: "Měsíc",
  year: "Rok",
  status: "Stav",
  importAttendanceFirstForMonth: "Nejdřív naimportujte docházku pro tento měsíc.",
  allMonths: "Všechny měsíce",
  selectMonths: "Vyberte měsíce",
  monthsCount: "{count} měsíců",
  onlyMonthsWithUnapprovedTimesheets: "Pouze měsíce s neschválenými výkazy",
  positions: "Pozice",
  filter: "Filtrovat",
  comments: "Komentáře",
  roleEmployee: "Zaměstnanec",
  roleManager: "Manažer",
  roleController: "Kontrolor",
  system: "Systém",
  loadCommentsFailed: "Nepodařilo se načíst komentáře.",
  sendCommentFailed: "Nepodařilo se odeslat komentář.",
  noCommentsYet: "Zatím žádné komentáře.",
  writeCommentPlaceholder: "Napište komentář…",
  sending: "Odesílám…",
  send: "Odeslat",
  day: "Den",
  clockIn: "Příchod",
  clockOut: "Odchod",
  breakStart: "Pauza od",
  breakEnd: "Pauza do",
  interruption: "Přerušení",
  attendance: "Docházka",
  nightWork: "Noční práce",
  control: "Kontrola",
  difference: "Rozdíl",
  noContractNumber: "Bez čísla zakázky",
  fillMissingHoursInTimesheet: "Doplnit chybějící hodiny v celém výkazu",
  fillRemainingHoursEmptyOnly: "Doplnit zbývající hodiny jen do prázdných polí",
};
