// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timesheets.Api.Data;

#nullable disable

namespace Timesheets.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711133125_RepointAttendanceDayToAttendance")]
    partial class RepointAttendanceDayToAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timesheets.Api.Data.Models.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("TimesheetId")
                        .IsUnique();

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("BreakEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("BreakStart")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ClockIn")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ClockOut")
                        .HasColumnType("interval");

                    b.Property<decimal>("CoreHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("HoursObligation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("HoursWithoutBreak")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsHoliday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Schedules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceDay", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceDay_WorkloadAndHours", "\"Workload\" >= 0 AND \"Workload\" <= 1\r\nAND \"HoursWithoutBreak\" >= 0\r\nAND \"HoursObligation\" >= 0\r\nAND \"CoreHours\" >= 0");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceTimesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimesheetStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("TimesheetStatusId");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("AttendanceTimesheet", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceTimesheet_ValidMonth", "\"Month\" >= 1 AND \"Month\" <= 12");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ContractEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.HasIndex("ContractId", "EmployeeId", "PositionCode", "StartDate")
                        .IsUnique();

                    b.ToTable("ContractEmployee", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContractEmployee_ValidDateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_ContractEmployee_WorkloadRange", "\"Workload\" >= 0 AND \"Workload\" <= 1");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ContractManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ContractId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("ContractManager", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.CoreEmployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("CoreEmployment", null, t =>
                        {
                            t.HasCheckConstraint("CK_CoreEmployment_ValidDateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_CoreEmployment_WorkloadRange", "\"Workload\" >= 0 AND \"Workload\" <= 1");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.DayInterruption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterruptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InterruptionId");

                    b.HasIndex("AttendanceDayId", "InterruptionId")
                        .IsUnique();

                    b.ToTable("DayInterruption", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsGlobalManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleAfter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TitleBefore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("Surname");

                    b.HasIndex("Surname", "FirstName");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.EmployeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Akademik"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Neakademik"
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.EmployeeWorkload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("EmployeeWorkload", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeWorkload_ValidMonth", "\"Month\" >= 1 AND \"Month\" <= 12");

                            t.HasCheckConstraint("CK_EmployeeWorkload_WorkloadRange", "\"Workload\" >= 0 AND \"Workload\" <= 1");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Interruption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("HoursObligationOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Interruption", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Dovolenka",
                            HoursObligationOverride = 0m,
                            Name = "D"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "práce na dálku od 1.10.2023",
                            Name = "JMV/HO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Karanténa -home office",
                            Name = "KAHO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Description = "Omluvená nepřítomnost - tvůrčí volno",
                            HoursObligationOverride = 0m,
                            Name = "M"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Description = "Mateřská dovolená / Otcovská dovolená",
                            HoursObligationOverride = 0m,
                            Name = "MD/OD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Description = "Nemocenská",
                            HoursObligationOverride = 0m,
                            Name = "N"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Description = "Neomluvená absence",
                            HoursObligationOverride = 0m,
                            Name = "NA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Description = "Návštěva lékaře - krátkodobá",
                            Name = "NK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Description = "Návštěva lékaře - celý den",
                            HoursObligationOverride = 0m,
                            Name = "NL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Description = "Pracovní úraz",
                            HoursObligationOverride = 0m,
                            Name = "NP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Description = "Náhradní volno za odprac. dobu",
                            HoursObligationOverride = 0m,
                            Name = "NV"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Description = "Ošetřovné",
                            HoursObligationOverride = 0m,
                            Name = "O"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Description = "Osobní překážky",
                            Name = "OPN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Description = "Narození dítěte",
                            HoursObligationOverride = 0m,
                            Name = "PN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Description = "Odběr krve",
                            Name = "PO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Description = "Svatba",
                            HoursObligationOverride = 0m,
                            Name = "PS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Description = "Úmrtí rod. příslušníka",
                            HoursObligationOverride = 0m,
                            Name = "PU"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Description = "Pracovní volno pro brannou povinnost",
                            HoursObligationOverride = 0m,
                            Name = "PVB"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Description = "Pracovní volno pro s akcí pro děti a mládež",
                            HoursObligationOverride = 0m,
                            Name = "PVM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Description = "Překážka na straně zaměstnavatele",
                            HoursObligationOverride = 0m,
                            Name = "PZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Description = "Rodičovská dovolená",
                            HoursObligationOverride = 0m,
                            Name = "RD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Description = "Tuzemská služební cesta Projekt",
                            Name = "SCP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Description = "Tuzemská služební cesta Stáž",
                            Name = "SCS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Description = "Služební cesta",
                            Name = "SCT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Description = "Služební cesta zahraniční",
                            Name = "SCZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Description = "Zahraniční služební cesta Erasmus",
                            Name = "SCZE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Description = "Zahraniční služební cesta Projekt",
                            Name = "SCZP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Description = "Zahraniční služební cesta Stáž",
                            Name = "SCZS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Description = "Studium s náhradou mzdy",
                            Name = "ST"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Description = "Neplacené volno",
                            HoursObligationOverride = 0m,
                            Name = "VN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Description = "Nové zaměstnání",
                            HoursObligationOverride = 0m,
                            Name = "VZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Description = "Volno pro obecný zájem",
                            HoursObligationOverride = 0m,
                            Name = "Z"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Description = "Veřejná funkce - poslanec",
                            Name = "Zp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Description = "Dlouhodobý pobyt v cizině",
                            Name = "Zs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Description = "Zdravotní volno",
                            HoursObligationOverride = 0m,
                            Name = "Zv"
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Project", null, t =>
                        {
                            t.HasCheckConstraint("CK_Project_ValidDateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("HoursLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("HoursObligation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsHoliday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectTimesheetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTimesheetId", "Date")
                        .IsUnique();

                    b.ToTable("ProjectDay", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectDay_HoursAndWorkload", "\"Hours\" >= 0\r\nAND \"Workload\" >= 0 AND \"Workload\" <= 1\r\nAND \"HoursObligation\" >= 0");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("ProjectManager", (string)null);
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectTimesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimesheetStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Workload")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimesheetStatusId");

                    b.HasIndex("ContractEmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProjectTimesheet", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectTimesheet_ValidMonth", "\"Month\" >= 1 AND \"Month\" <= 12");

                            t.HasCheckConstraint("CK_ProjectTimesheet_WorkloadRange", "\"Workload\" >= 0 AND \"Workload\" <= 1");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimesheetStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("TimesheetStatusId");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Timesheet", null, t =>
                        {
                            t.HasCheckConstraint("CK_Timesheet_ValidMonth", "\"Month\" >= 1 AND \"Month\" <= 12");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttendanceTimesheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectTimesheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceTimesheetId");

                    b.HasIndex("AuthorEmployeeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectTimesheetId");

                    b.ToTable("TimesheetComment", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimesheetComment_ExactlyOneTimesheet", "(\"AttendanceTimesheetId\" IS NOT NULL AND \"ProjectTimesheetId\" IS NULL)\r\nOR\r\n(\"AttendanceTimesheetId\" IS NULL AND \"ProjectTimesheetId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TimesheetStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Code = "DRAFT",
                            Name = "Rozpracovaný"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Code = "SUBMITTED",
                            Name = "Ke schválení"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Code = "APPROVED",
                            Name = "Schválený"
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttendanceTimesheetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectTimesheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceTimesheetId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByEmployeeId");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ProjectTimesheetId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("TimesheetStatusHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimesheetStatusHistory_ExactlyOneTimesheet", "(\"AttendanceTimesheetId\" IS NOT NULL AND \"ProjectTimesheetId\" IS NULL)\r\nOR\r\n(\"AttendanceTimesheetId\" IS NULL AND \"ProjectTimesheetId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Attendance", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Timesheet", "Timesheet")
                        .WithOne("Attendance")
                        .HasForeignKey("Timesheets.Api.Data.Models.Attendance", "TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceDay", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Attendance", "Attendance")
                        .WithMany("Days")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceTimesheet", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany("AttendanceTimesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.EmployeeType", null)
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timesheets.Api.Data.Models.TimesheetStatus", "TimesheetStatus")
                        .WithMany("AttendanceTimesheets")
                        .HasForeignKey("TimesheetStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("TimesheetStatus");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Contract", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Project", "Project")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ContractEmployee", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Contract", "Contract")
                        .WithMany("ContractEmployees")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ContractManager", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Contract", "Contract")
                        .WithMany("ContractManagers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.CoreEmployment", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany("CoreEmployments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.DayInterruption", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.AttendanceDay", "AttendanceDay")
                        .WithMany("DayInterruptions")
                        .HasForeignKey("AttendanceDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Interruption", "Interruption")
                        .WithMany()
                        .HasForeignKey("InterruptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceDay");

                    b.Navigation("Interruption");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Employee", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.EmployeeWorkload", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany("EmployeeWorkloads")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Notification", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectDay", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.ProjectTimesheet", "ProjectTimesheet")
                        .WithMany("Days")
                        .HasForeignKey("ProjectTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTimesheet");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectManager", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Project", "Project")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectTimesheet", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.ContractEmployee", null)
                        .WithMany()
                        .HasForeignKey("ContractEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Contract", null)
                        .WithMany("ProjectTimesheets")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.Employee", null)
                        .WithMany("ProjectTimesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.TimesheetStatus", "TimesheetStatus")
                        .WithMany()
                        .HasForeignKey("TimesheetStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimesheetStatus");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Timesheet", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.TimesheetStatus", "TimesheetStatus")
                        .WithMany()
                        .HasForeignKey("TimesheetStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("TimesheetStatus");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetComment", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.AttendanceTimesheet", "AttendanceTimesheet")
                        .WithMany("Comments")
                        .HasForeignKey("AttendanceTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "AuthorEmployee")
                        .WithMany()
                        .HasForeignKey("AuthorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.ProjectTimesheet", "ProjectTimesheet")
                        .WithMany("Comments")
                        .HasForeignKey("ProjectTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AttendanceTimesheet");

                    b.Navigation("AuthorEmployee");

                    b.Navigation("ProjectTimesheet");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetStatusHistory", b =>
                {
                    b.HasOne("Timesheets.Api.Data.Models.AttendanceTimesheet", "AttendanceTimesheet")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AttendanceTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Timesheets.Api.Data.Models.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timesheets.Api.Data.Models.TimesheetStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timesheets.Api.Data.Models.ProjectTimesheet", "ProjectTimesheet")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ProjectTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Timesheets.Api.Data.Models.TimesheetStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceTimesheet");

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("FromStatus");

                    b.Navigation("ProjectTimesheet");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Attendance", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceDay", b =>
                {
                    b.Navigation("DayInterruptions");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.AttendanceTimesheet", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Contract", b =>
                {
                    b.Navigation("ContractEmployees");

                    b.Navigation("ContractManagers");

                    b.Navigation("ProjectTimesheets");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Employee", b =>
                {
                    b.Navigation("AttendanceTimesheets");

                    b.Navigation("CoreEmployments");

                    b.Navigation("EmployeeWorkloads");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectTimesheets");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Project", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("ProjectManagers");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.ProjectTimesheet", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Days");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.Timesheet", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Timesheets.Api.Data.Models.TimesheetStatus", b =>
                {
                    b.Navigation("AttendanceTimesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
